apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: ZWNvbW1lcmNl  # Base64 de "ecommerce"
  POSTGRES_PASSWORD: UGcxMjM0  # Base64 de "Pg1234"
  POSTGRES_DB: ZWNvbW1lcmNl  # Base64 de "ecommerce"
